### PR TITLE
Issue #12: tag metrics on startup

### PR DESCRIPTION
**Pull request by jotak**
It uses a listener on the registry to know whenever a metric is created.

@jsanda I haven't tested it for real, but there's a small set of unit & integration tests that are OK. Do you plan to test with the cassandra reporter?

### CODE REVIEW

**Comment by jsanda** [comment]
Yes, I will test your changes with Cassandra.

**Comment by jsanda** [comment]
The changes LGTM, but I am not able to test them. At start up I get:

```
INFO  [main] 2016-12-07 13:24:01,904 CassandraDaemon.java:358 - Trying to load metrics-reporter-config from file: hawkular-reporter.yaml
ERROR [main] 2016-12-07 13:24:02,084 HawkularReporterConfig.java:187 - Failed to enable HawkularReporter
java.lang.RuntimeException: Could not tag metric jvm.buffers..direct.capacity
        at org.hawkular.metrics.dropwizard.MetricsTagger.tagMetric(MetricsTagger.java:103) ~[hawkular-dropwizard-reporter-0.1.0-SNAPSHOT-shaded.jar:0.1.0-SNAPSHOT]
        at org.hawkular.metrics.dropwizard.MetricsTagger.onGaugeAdded(MetricsTagger.java:109) ~[hawkular-dropwizard-reporter-0.1.0-SNAPSHOT-shaded.jar:0.1.0-SNAPSHOT]
        at java.util.TreeMap.forEach(TreeMap.java:1005) ~[na:1.8.0_102]
        at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[na:1.8.0_102]
        at org.hawkular.metrics.dropwizard.MetricsTagger.<init>(MetricsTagger.java:58) ~[hawkular-dropwizard-reporter-0.1.0-SNAPSHOT-shaded.jar:0.1.0-SNAPSHOT]
        at org.hawkular.metrics.dropwizard.HawkularReporter.<init>(HawkularReporter.java:62) ~[hawkular-dropwizard-reporter-0.1.0-SNAPSHOT-shaded.jar:0.1.0-SNAPSHOT]
        at org.hawkular.metrics.dropwizard.HawkularReporterBuilder.build(HawkularReporterBuilder.java:238) ~[hawkular-dropwizard-reporter-0.1.0-SNAPSHOT-shaded.jar:0.1.0-SNAPSHOT]
        at com.addthis.metrics3.reporter.config.HawkularReporterConfig.enable(HawkularReporterConfig.java:183) ~[reporter-config3-3.0.4-SNAPSHOT.jar:3.0.4-SNAPSHOT]
        at com.addthis.metrics3.reporter.config.ReporterConfig.enableHawkular(ReporterConfig.java:275) [reporter-config3-3.0.4-SNAPSHOT.jar:3.0.4-SNAPSHOT]
        at com.addthis.metrics3.reporter.config.ReporterConfig.enableAll(ReporterConfig.java:311) [reporter-config3-3.0.4-SNAPSHOT.jar:3.0.4-SNAPSHOT]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:368) [main/:na]
```

Looks like the [failure management ticket](https://github.com/hawkular/hawkular-dropwizard-reporter/issues/16) might be needed first.

**Comment by jotak** [comment]
replaced with PR #18

**Comment by jotak** [comment]
@jsanda the new PR (#18) should resolve the errors you see at startup

**Pull request closed without merging**
