### PR TITLE
Issues #12, #13, #16

### PR DESCRIPTION
**Pull request by jotak**
- Tag metrics on startup
- Merge rest calls counters/gauges into 1 call to metrics
- Failure management

### CODE REVIEW

**Comment by jsanda** [comment]
I will go ahead and test now.

**Comment by jsanda** [comment]
It looks like the pattern filtering is broken with this PR. In my metrics-reporter-config conf file I have:

```
predicate:
      useQualifiedName: true
      color: 'white'
      patterns:
        - 'org\.apache\.cassandra\.metrics\.CommitLog\..*'
```

and I am now getting all metrics Cassandra, not just the CommitLog metrics.

**Comment by jsanda** [comment]
I found the issue. MetricRegistry does not apply the filter when notifying listeners. If anything, I would consider it a bug in MetricRegistry. I pushed a fix [here](https://github.com/jsanda/hawkular-dropwizard-reporter/tree/failure-management).

**Comment by jotak** [comment]
Thanks, it's merged here

**Pull request merged**
