### PR TITLE
[HAWKULAR-1126] First draft for dropwizard reporter

### PR DESCRIPTION
**Pull request by jotak**
Manages gauges, counters, meters (as gauges in hawkular)

Note that it depends on hawkular-java-client PR https://github.com/hawkular/hawkular-client-java/pull/42
And it would be probably better to release the java-client and point to the released version before merging this

### CODE REVIEW

**Comment by tsegismont** [comment]
I have the feeling that depending on the Hawkular Java client is going to be a source of conflicts, since it will transitively pull a lot of jars (guava, jax-rs client among others).

Since the only interaction required is an HTTP POST to a `data/raw` endpoint, you might just use the JDK's HttpClient and format JSON manually.

**Comment by tsegismont** [comment]
Note for implementation: Dropwizard's gauges present a single value, where as timers and meters present several (five minutes ratio, 95th percentile, ...etc). It would be good to have those values stored as well. Note that for ratios, there is a JMX field indicating the unit.

Also, we might want to add tags to the metrics to determine if it's a 95th percentile, a ratio, ...etc.

**Comment by jsanda** [comment]
I have similar reservations about using the Hawkular client. We want something that is going to be light weight. I don't think that has to rule out anything other than the JDK.

**Comment by pilhuhn** [comment]
On 7 Oct 2016, at 15:25, jsanda wrote:

> I have similar reservations about using the Hawkular client. We want 
> something that is going to be light weight. I don't think that has to 
> rule out anything other than the JDK.

I wonder though, if it would make sense to pull in OkHttp
in order to potentially leverage http2, which WildFly 10 supports
with only minimal changes (it needs ssl + an external lib in
the boot-classpath + enabling of it in the undertow subsystem).

**Comment by jotak** [comment]
I came to the same conclusions after having some pain in integrating this dropwizard reporter in an existing app (jar conflicts etc.) , i'll rewrite it without hawkular java client.

(My initial idea was to make our java client more used but it turned out to be not so good)

**Comment by jsanda** [comment]
I am specifically looking to use this within Cassandra so we can easily collect metrics and monitor it. It already has support for pluggable reporters which makes things even easier. Take a look at http://www.datastax.com/dev/blog/pluggable-metrics-reporting-in-cassandra-2-0-2 if you haven't already.

**Comment by jotak** [comment]
About JDK client vs OkHttp Vs any other: I can create a very simple interface for the http layer, that would default to the JDK one, and allows any containing application to use whatever it likes instead.

I can also write other implementations, like OkHttp (or Apache or whatever) as separate maven modules to make things easier for any potential user (but that would be for another PR if you agree)

**Comment by jotak** [comment]
Note: the interface would be something as simple as:

```
public interface HawkularHttpClient {
    void addHeaders(Map<String, String> headers);
    HawkularHttpResponse postMetric(String endpoint, String jsonBody);
}
```

**Comment by jotak** [comment]
For information there's still some work to do (I've opened some issues: https://github.com/hawkular/hawkular-dropwizard-reporter/issues) but I think this first PR can be merged at this level of functionality if code review is fine.

**Comment by jotak** [comment]
@jsanda I must try it plugged with cassandra... maybe tomorrow

**Comment by jotak** [comment]
@jsanda , you were right about Cassandra and the "addthis" reporter-config ( https://github.com/addthis/metrics-reporter-config ). We must open a PR there to plug in our dropwizard reporter. I've forked it to check that and, indeed, I can get the cassandra metrics in hawkular.

Anyway, I suggest merging this PR first, then open another one to addthis/metrics-reporter-config (and I hope it will be merged too)

**Pull request merged**
